export const COURSES = {
  GET_START: 'COURSES.GET_START',
  GET_SUCCESS: 'COURSES.GET_SUCCESS',
};

export const COURSE = {
  GET_START: 'COURSE.GET_START',
  GET_SUCCESS: 'COURSE.GET_SUCCESS',
  SET_PROGRESS: 'COURSE.SET_PROGRESS',
  RESET: 'COURSE.RESET',
};
